# Goal
string video_path            # Path to the video file
string class_name            # Class name of the object to find
int32 max_frames             # Maximum number of frames to process
float32 confi_threshold      # Threshold for the object detection

---
# Result
bool success                 # True if the object was found
int32 frames_number          # Number of frames processed
# string error_message         # Error message if the object was not found

---
# Feedback
int32 frames_number          # Number of frames processed so far